// Generated by CoffeeScript 1.7.1
(function() {
  var layer, shortcuts;

  shortcuts = require("shortcuts");

  shortcuts.initialize();

  layer = new Layer;

  layer.center();

  layer.click(function() {
    return layer.animateTo({
      y: 500
    }, function() {
      return layer.fadeOut();
    });
  });

}).call(this);
